Add build tag option
launchdarkly/go-options pull request #25
Opened 2024-05-28 10:50 UTC by hoshsadiq

2024-05-28 11:19 UTC, ldhenry reviewed
This looks good. But what's the reason for doing this? Is there a shortcut story somewhere?

2024-06-11 09:57 UTC, BehnH requested changes

2024-06-11 09:57 UTC, BehnH commented on .github/workflows/build.yml
> +    - uses: actions/checkout@v4.1.0
We should use SHAs for external actions as noted in the SDR

```suggestion
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
```

2024-06-11 09:57 UTC, BehnH commented on .github/workflows/build.yml
> +    - uses: actions/setup-go@v5
Same here 

```suggestion
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
```

2024-07-02 10:04 UTC, ldhenry approved these changes

2024-07-02 10:07 UTC, merged